
[PhysicsEngine]

damping = 0.3

[Scenario]

name = 'Objective.goto'
debug = true

[[Ship]]

name = 'FireFive'
model = '..firefive'
controller = '..goals/firefive_goto.py'

x = 0
y = 0
angle = 0

[[Image]]

path = '..basic/target.png'
x = 100
y = 0

width = 35

[[Image]]

path = '..basic/target.png'
x = 200
y = 160

width = 35

[[Image]]

path = '..basic/target.png'
x = -120
y = 330

width = 35

[[Image]]

path = '..basic/target.png'
x = -50
y = -50

width = 35

[[Image]]

path = '..basic/target.png'
x = 10
y = 300

width = 35

[[Image]]

path = '..basic/target.png'
x = 400
y = 400

width = 35

[[Objective]]

type = 'goto'

x = 100
y = 0

distance = 50

[[Objective]]

type = 'goto'

x = 200
y = 160

distance = 50

[[Objective]]

type = 'goto'

x = -120
y = 330

distance = 50

[[Objective]]

type = 'goto'

x = -50
y = -50

distance = 50

[[Objective]]

type = 'goto'

x = 10
y = 300

distance = 50

[[Objective]]

type = 'goto'

x = 400
y = 400

distance = 50
