
[Scenario]

name = 'Objective.list.required_quantity'
debug = true

[[Ship]]

name = 'ship'
model = '..basic/go_forward'
controller = '..basic/go_forward.py'

x = 0
y = 0
angle = 0

[[Objective]]

type = 'list'

x = 0
y = 0

required_quantity = 2
distance = 50

    [[Objective.Objective]]

    type = 'goto'

    x = 0
    y = 0

    distance = 10

    [[Objective.Objective]]

    type = 'goto'

    x = 200
    y = 0

    distance = 10

    [[Objective.Objective]]

    type = 'goto'

    x = 400
    y = 0

    distance = 10
