
[[Shape]]

type = 'circle'
mass = 10
radius = 15
elasticity = 0.95
friction = 0.9

[[Part]]

name = 'part'
x = 0
y = 0

[[Communication]]

part = 'part'

type = 'sender'
model = 'configurable'

intensity = 1e6
frequency = 10000

[Communication.Error.Intensity]

error_max = 3e4 # noise will also cause error
offset_max = 1e5
