
[Scenario]

name = 'example1'
debug = true

[[Ship]]

id = 'main-ship'
name = 'sender'
model = '.basic_sender'
controller = '.basic_sender.py'

x = 0
y = 0
angle = 45

[[Ship]]

id = 'main-ship'
name = 'receiver'
model = '.basic_receiver'
controller = '.basic_receiver.py'

x = 100
y = 100
angle = -45
