
[[Shape]]

type = 'circle'
mass = 10
radius = 50
elasticity = 0.95
friction = 0.9

[[Shape]]

type = 'circle'
mass = 1
radius = 10
elasticity = 0.95
friction = 0.9
y = 60

[[Shape]]

type = 'circle'
mass = 1
radius = 10
elasticity = 0.95
friction = 0.9
y = -60

[[Shape]]

type = 'polygon'
mass = 3

    [[Shape.Point]]

    x = -40
    y = -70

    [[Shape.Point]]

    x = -40
    y = 70

    [[Shape.Point]]

    x = -60
    y = -70

    [[Shape.Point]]

    x = -60
    y = 70

[[Part]]

name = 'part1'
x = 0
y = 0

[[Part]]

name = 'part2'
x = 0
y = 25

[[Sensor]]

part = 'part1'

name = 'pos-sensor'
type = 'position'

reading_time = 1

error_max = 100
offset_max = 40

[[Sensor]]

part = 'part1'

name = 'ang-sensor'
type = 'angle'

reading_time = 5

error_max = 10
offset_max = 2

[[Sensor]]

part = 'part1'

name = 'speed-sensor'
type = 'speed'

reading_time = 0.5

[[Actuator]]

part = 'part1'

name = 'engine1'
type = 'engine'
model = 'intensity_range'

min_intensity = -4
max_intensity = 4

min_angle = 0
max_angle = 0

[Actuator.Error.Position]

error_max = 30
offset_max = 30

[[Actuator]]

part = 'part2'

name = 'engine2'
type = 'engine'
model = 'intensity_range'

min_intensity = 0
max_intensity = 4

min_angle = 0
max_angle = 0

intensity_mult = 4

[[Actuator]]

part = 'part2'

name = 'engine3'
type = 'engine'
model = 'intensity_range'

min_intensity = 0
max_intensity = 4

min_angle = 0
max_angle = 0

[[InterfaceDevice]]

part = 'part2'

name = 'display1'
type = 'text-display'

x = 30
y = 30
height = 15
width = 160

[[InterfaceDevice]]

part = 'part2'

name = 'button1'
type = 'button'

x = 30
y = 70

[[InterfaceDevice]]

part = 'part2'

name = 'kb1'
type = 'keyboard'

x = 210
y = 28

[[InterfaceDevice]]

part = 'part2'

name = 'display2'
type = 'text-display'
model = 'console'

x = 10
y = 200
columns = 25
rows = 15
