
[Inheritance]

parent = '.ship1'

[[Shape]]

id = 'poly-shape'
type = 'polygon'
mass = 3

    [[Shape.Point]]

    id = 'p1'

        [Shape.Point.Inheritance]

        mode = 'delete'

    [[Shape.Point]]

    id = 'p2'
    y = 0
