
[Metadata]

name = 'Introduction'
description = 'Basic instructions to understand tha base of scenario making'

[[Block]]

type = "paragraph"
content = """
    The scenario making is divided in four main types of files that may be used.
    In this page you'll find a little bit about each of them.
"""

[[Block]]

type = "list"

    [[Block.Item]]

        content = 'Scenario'

    [[Block.Item]]

        content = 'Ship Model'

    [[Block.Item]]

        content = 'Controller'

    [[Block.Item]]

        content = 'Object Model'

[[Block]]

type = "break"

[[Block]]

type = "paragraph"
content = "Scenario:"

[[Block]]

type = "paragraph"
content = """
    In the scenario file you'll be specify the number of ships and their's \
    position, controller and model as the number of objects, their's position\
    and model. You will be able to specify here the objectives the controller\
    need to accomplish as well.
"""

[[Block]]

type = "paragraph"
content = "Ship Model:"

[[Block]]

type = "paragraph"
content = """
    The ship model file will describe the ships physical properties, it's \
    appearance and all devices it has.
"""

[[Block]]

type = "paragraph"
content = "Object Model:"

[[Block]]

type = "paragraph"
content = """
    The object model file will describe all physical properties that describe \
    an object.
"""

[[Block]]

type = "paragraph"
content = "Controller:"

[[Block]]

type = "paragraph"
content = """
    The controller file must be an executable file that will used to control a \
    ship. It can control a ship interacting with its devices.
"""
