
[Configuration]

mode = 'static'

type = 'test'

[ModelInfo]

type = 'list'

sequential = true

    [[ModelInfo.Objective]]

    type = 'goto'

    x = 0
    y = 0

    distance = 10

    [[ModelInfo.Objective]]

    type = 'goto'

    x = 400
    y = 0

    distance = 10

    [[ModelInfo.Objective]]

    type = 'goto'

    x = 200
    y = 0

    distance = 10
