
[Configuration]

type = 'test'
model = 'test'

[Info]

type = 'list'

sequential = true

    [[Objective.Objective]]

    type = 'goto'

    x = 0
    y = 0

    distance = 10

    [[Objective.Objective]]

    type = 'goto'

    x = 400
    y = 0

    distance = 10

    [[Objective.Objective]]

    type = 'goto'

    x = 200
    y = 0

    distance = 10
