
[Configuration]

mode = 'dynamic'

type = 'test2'

[ModelInfo]

type = 'list'

sequential = true

    [[ModelInfo.Objective]]

    type = 'goto'

    x = 0
    y = 0

    distance = 10

    [[ModelInfo.Objective]]

    type = 'goto'

    x = 'var# var1'
    y = 0

    distance = 10

    [[ModelInfo.Objective]]

    type = 'goto'

    x = 200
    y = 0

    distance = 10
