
[Configuration]

mode = 'static'

function_type = 'InterfaceDevice'
type = 'device1'

[ModelInfo]

function_type = 'InterfaceDevice'
type = 'text-display'
model = 'console'

x = 10
y = 150
columns = 25
rows = 15
