
[Scenario]

name = 'example2'

[[Ship]]

id = 's1'
name = 'ship1'
model = 'examples/ship1'
controller = 'examples/ship1_control_example.py'

x = 50
y = 100
angle = 45

[[Ship]]

id = 's2'
name = 'ship2'
model = 'examples/ship1'
controller = 'examples/ship1_control_example.py'

x = 50
y = 100
angle = -45

[[Ship]]

id = 's3'
name = 'ship3'
model = 'examples/ship1'
controller = 'examples/ship1_control_example.py'

x = 200
y = 100
