
[Inheritance]

parent = '.scenario2'

[Scenario]

hide_user_interface = true

[[Ship]]

id = 's1'
model = ['.ship1', '.ship2']
x = -100
y = 0

[[Ship]]

id = 's2'

    [Ship.Inheritance]

    mode = 'delete'

[[Objective]]

type = 'list'

    [[Objective.Objective]]

    type = 'goto'

    x = 200
    y = 200

    distance = 50

    [[Objective.Objective]]

    type = 'goto'

    x = 500
    y = 500

    distance = 100

[[Objective]]

type = 'goto'

x = 1100
y = 1100

distance = 200
