
[Scenario]

name = 'example1'

[[Ship]]

name = 'ship1'
model = 'examples/ship1'
controller = 'examples/ship1_control_example.py'

x = 50
y = 100
angle = 45

[[Ship]]

name = 'ship2'
model = 'examples/ship1'
controller = 'examples/ship1_control_example.py'

x = 50
y = 100
angle = -45
