
[Metadata]

name = 'Shortcuts'
description = 'Program shortcuts'

[[Block]]

type = 'list'

    [[Block.Item]]

    content = "'Ctrl' + '=' = zoom in"

    [[Block.Item]]

    content = "'Ctrl' + '-' = zoom out"

    [[Block.Item]]

    content = "'Ctrl' + 'R' = restore zoom"
