
[Metadata]

name = 'Shortcuts'
description = 'Program shortcuts'

[[Block]]

type = "paragraph"
content = "'Ctrl' + '=' = zoom in"

[[Block]]

type = "paragraph"
content = "'Ctrl' + '-' = zoom out"

[[Block]]

type = "paragraph"
content = "'Ctrl' + 'R' = restore zoom"
