
[Metadata]

name = 'Shortcuts'
description = 'Program shortcuts'

[[Paragraph]]

content = "'Ctrl' + '=' = zoom in"

[[Paragraph]]

content = "'Ctrl' + '-' = zoom out"

[[Paragraph]]

content = "'Ctrl' + 'R' = restore zoom"
