
[Config]

variables_enabled = true
static = true

[[Variable]]

id = 'size'
value = 100
override = false

[[Variable]]

id = 'thickness'
value = 2.5
override = false

[[Shape]]

id = 'line'
type = 'line'
thickness = 'var# thickness'

    [[Shape.Point]]

    id = 'begin'
    x = 'expr# -size/2'

    [[Shape.Point]]

    id = 'end'
    x = 'expr# size/2'

